In [72]:
import pandas as pd
import numpy as np

In [74]:
bike=pd.read_csv('BikeDetails.csv')

In [76]:
bike

name  selling_price  year seller_type  \
0               Royal Enfield Classic 350         175000  2019  Individual   
1                               Honda Dio          45000  2017  Individual   
2     Royal Enfield Classic Gunmetal Grey         150000  2018  Individual   
3       Yamaha Fazer FI V 2.0 [2016-2018]          65000  2015  Individual   
4                   Yamaha SZ [2013-2014]          20000  2011  Individual   
...                                   ...            ...   ...         ...   
1056                            Activa 3g          17000  2010  Individual   
1057                     Honda CB twister          16000  2012  Individual   
1058                   Bajaj Discover 125          15000  2013  Individual   
1059                       Honda CB Shine          12000  2009  Individual   
1060                     Bajaj Pulsar 150          10000  2008  Individual   

          owner  km_driven  ex_showroom_price  
0     1st owner        350                NaN  
1     1st owner       5650                NaN  
2     1st owner      12000           148114.0  
3     1st owner      23000            89643.0  
4     2nd owner      21000                NaN  
...         ...        ...                ...  
1056  1st owner     500000            52000.0  
1057  1st owner      33000            51000.0  
1058  2nd owner      35000            57000.0  
1059  1st owner      53000            58000.0  
1060  1st owner      92233            75000.0  

[1061 rows x 7 columns]

In [78]:
bike.drop(columns=['ex_showroom_price', 'owner','seller_type'], inplace=True)

In [80]:
bike

name  selling_price  year  km_driven
0               Royal Enfield Classic 350         175000  2019        350
1                               Honda Dio          45000  2017       5650
2     Royal Enfield Classic Gunmetal Grey         150000  2018      12000
3       Yamaha Fazer FI V 2.0 [2016-2018]          65000  2015      23000
4                   Yamaha SZ [2013-2014]          20000  2011      21000
...                                   ...            ...   ...        ...
1056                            Activa 3g          17000  2010     500000
1057                     Honda CB twister          16000  2012      33000
1058                   Bajaj Discover 125          15000  2013      35000
1059                       Honda CB Shine          12000  2009      53000
1060                     Bajaj Pulsar 150          10000  2008      92233

[1061 rows x 4 columns]

In [82]:
bike['year'].unique()

array([2019, 2017, 2018, 2015, 2011, 2010, 2008, 2016, 2020, 2012, 2006,
       2013, 2009, 2014, 2004, 2007, 2000, 2002, 2005, 1997, 2001, 1988,
       1999, 1998, 1991, 2003, 1993, 1995])

In [84]:
bike['selling_price'].unique()

array([175000,  45000, 150000,  65000,  20000,  18000,  78500, 180000,
        30000,  50000,  35000,  28000,  80000, 365000, 185000,  25000,
        40000, 120000,  15000,  26000,  32000, 110000,  42000,  21000,
        55000,  38000,  43000,  62000,  60000,  90000, 125000,  85000,
        29900,  70000,  48000,  34000, 165000,  29500,  95000,   7500,
       160000, 140000,  22000,  22989,  24999,  75000,  17500,  57000,
        83900, 135000, 299000, 750000, 190000, 130000,  54786,  72000,
       100000, 138000, 170000, 123000,  23000,  41000,  47999,  36999,
        12000,  27000,  10000,  56000,  58000,  87000, 145000,   9000,
        14000,  17000, 210000,  54000, 260000,  98000, 200000, 195000,
       270000, 425000, 760000,  37000, 330000, 162000, 285000,  69000,
       300000,  26500,  78000,   8000,  39000,  36000,  16000,  83299,
        14700,  19000,  14900,  24000,  24700,  52000,  47000, 105000,
       115000,   5000,  86000,  28700,   6000,  23500,  68000,  20100,
      

In [86]:

bike['km_driven'].unique()

array([   350,   5650,  12000,  23000,  21000,  60000,  17000,  39000,
        32000,  42000,  10000,  21178,   1127,   1700,  55000,  27000,
        45000,  17450,  20696,   2000,  20000,  35000,  15210,  24000,
         2500,  75000,  50000,   6502,  16000,  13000,  12800,   4600,
        81000,   8000,  57000,  26000,  29000,  43000,  40000,   3000,
        80000,  30000,  41000,   8150,   1933,  55750,  15856,   3700,
        21938,  48000,  54000,  15000,   3500,   9000,  38000,  22000,
         9432,  70000, 500000,  30514, 130000,  25000,  22770,   6330,
          500,  43400,   7004,  16500,  12500,   9600,  11000,   7500,
       120000,   6465,  18803,   7000,   6100,  14000,  85000,  18000,
         1500,  90000,  36500,  49000,   8500,   3775,  14500,   4000,
        99000,  52000,   2300,  36000,  71000,  15888,   5600,  19612,
        33700, 100000,   6000,  46000,  72000,  67000,  15500,  60855,
        37714,  34601,  44000,  17500,   6500,   2200,  66191,  32800,
      

In [88]:
bike['name']=bike['name'].str.split(' ').str.slice(0,3).str.join(' ')

In [90]:
bike

name  selling_price  year  km_driven
0     Royal Enfield Classic         175000  2019        350
1                 Honda Dio          45000  2017       5650
2     Royal Enfield Classic         150000  2018      12000
3           Yamaha Fazer FI          65000  2015      23000
4     Yamaha SZ [2013-2014]          20000  2011      21000
...                     ...            ...   ...        ...
1056              Activa 3g          17000  2010     500000
1057       Honda CB twister          16000  2012      33000
1058     Bajaj Discover 125          15000  2013      35000
1059         Honda CB Shine          12000  2009      53000
1060       Bajaj Pulsar 150          10000  2008      92233

[1061 rows x 4 columns]

In [105]:
bike['year'] = bike['year'] + 2

In [107]:
bike.to_csv('Cleaned_bike.csv')

In [110]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
bike = pd.read_csv('Cleaned_bike.csv')
X = bike.drop(['selling_price', 'Unnamed: 0'], axis=1)
y = bike['selling_price']
numerical_features = ['km_driven', 'year']
categorical_features = ['name']
numerical_transformer = StandardScaler()
categorical_transformer = OneHotEncoder(handle_unknown='ignore')
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ])
pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                           ('regressor', LinearRegression())])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)
r2 = r2_score(y_test, y_pred)
print(f"R-squared score: {r2}")

R-squared score: 0.7514138842416163


In [112]:
scores=[]
for i in range(1000):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    pipeline.fit(X_train, y_train)
    y_pred = pipeline.predict(X_test)
    r2 = r2_score(y_test, y_pred)
    scores.append(r2)
scores[np.argmax(scores)]

0.7514138842416163

In [113]:
import pickle

In [114]:
pickle.dump(pipeline,open('LinearRegressionModel_Bike.pkl','wb'))